backend/src/main/java/com/borathings/borapagar/course/CourseEntity.java
backend/src/main/java/com/borathings/borapagar/subject/SubjectEntity.java

Foi apontado na última reunião do projeto. É interessante deixar explícitas todas as constraints dos nossos campos. Mesmo que a validação esteja sendo feita a nível de banco de dados.
Foram adicionadas as anotações `NotNull` nos atributos necessários da entidade de curso e disciplina

fix: adding NotNull annotation to entities

---

.github/workflows/backend.yml
.github/workflows/test_coverage.yml
backend/lombok.config
backend/pom.xml
backend/src/main/java/com/borathings/borapagar/config/SwaggerConfig.java

Aprimoração das ferramentas de revisão de código
- Configuração de informações do projeto na página do Swagger
- Configuração da dependência do Jacoco no pom.xml
- Configuração da CI de cobertura de testes utilizando relatório do Jacoco

Feat: configurar swagger(detalhes) e relátorio/CI com Jacoco  

---

frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/tailwind.config.js

Inserir no projeto o design system criado no figma 
closes #65
* Adiciona biblioteca de ícones
* Adiciona cores do figma no arquivo de config do tailwind
* Adiciona fonte Inter

Feat: add design system

---

backend/src/main/java/com/borathings/borapagar/core/AbstractModel.java
backend/src/main/java/com/borathings/borapagar/course/CourseEntity.java
backend/src/main/java/com/borathings/borapagar/course/dto/CourseDTO.java
backend/src/main/java/com/borathings/borapagar/subject/SubjectEntity.java
backend/src/main/java/com/borathings/borapagar/subject/dto/SubjectDTO.java
backend/src/test/java/com/borathings/borapagar/course/CourseControllerTests.java
backend/src/test/java/com/borathings/borapagar/course/CourseServiceTests.java
backend/src/test/java/com/borathings/borapagar/subject/SubjectControllerTests.java
backend/src/test/java/com/borathings/borapagar/subject/SubjectServiceTests.java

Essa é uma parte para resolver a issue #66. A motivação consta na issue. 
Utilização do builder em vez do construtor nas entidades de curso e disciplina
Builder na entidade de usuário que ainda está para ser mergeada, e também na entidade que relaciona curso e disciplina

fix: Usando builder nas entidades de curso e disciplina

---

backend/src/main/java/com/borathings/borapagar/user/UserService.java
backend/src/test/java/com/borathings/borapagar/user/UserServiceTests.java

Para o endpoint de matrícula é necessário que a gente possa encontrar o usuário autenticado dado o seu googleId. Além disso, o builder facilitará quando o relacionamento de matrícula entre usuários e turmas for adicionado.  Como são peças de código por si só desvinculadas do endpoint de matrícula, elas merecem uma PR própria. 
- Novo método `findByGoogleIdOrError` no service de usuário
- Utilização do builder no service e nos testes.

feat: preparando o userService para o endpoint de matrícula

---

backend/src/main/java/com/borathings/borapagar/classroom/ClassroomRepository.java
backend/src/main/java/com/borathings/borapagar/classroom/ClassroomService.java
backend/src/test/java/com/borathings/borapagar/classroom/ClassroomServiceTests.java

O endpoint de matrícula descrito em #81 precisa de métodos relacionados à entidade classroom. Estes métodos merecem uma PR própria por serem uma peça de código a parte do endpoint de matrícula
- Um repositório da entidade classroom
- Um service da entidade contendo um método que encontra uma turma pelo id.

feat: preparando classroom para endpoint de matrícula

---

frontend/src/components/BpInputUpload.vue

Criação do componente personalizado de upload de arquivos. Closes #88  
Componente separado e personalizado de acordo com o design system do figma.
**Screenshots** 
**Exemplo de uso**

feat: new upload component

---

backend/src/main/java/com/borathings/borapagar/core/AbstractModel.java
backend/src/main/resources/db/migration/V1.20240818230958__ALTER_TABLES_ADD_CREATED_AT_UPDATED_AT.sql

"Meta" campos que podem ser utéis para debugging, análise, B.I, etc.
- Adicionado os atributos`createdAt` e `updatedAt` em `AbstractModel`
- Adicionado os campos  `created_at` e `updated_at` nas tabelas que estão na main.

feat: adiciona campos created_at e updated_at

---

backend/src/main/java/com/borathings/borapagar/classroom/ClassroomEntity.java
backend/src/main/java/com/borathings/borapagar/classroom/ClassroomRepository.java
backend/src/main/java/com/borathings/borapagar/core/AbstractModel.java
backend/src/main/java/com/borathings/borapagar/core/AbstractRepository.java
backend/src/main/java/com/borathings/borapagar/core/SoftDeletableModel.java
backend/src/main/java/com/borathings/borapagar/core/SoftDeletableRepository.java
backend/src/main/java/com/borathings/borapagar/course/CourseEntity.java
backend/src/main/java/com/borathings/borapagar/course/CourseRepository.java
backend/src/main/java/com/borathings/borapagar/course/CourseService.java
backend/src/main/java/com/borathings/borapagar/subject/SubjectEntity.java
backend/src/main/java/com/borathings/borapagar/subject/SubjectRepository.java
backend/src/main/java/com/borathings/borapagar/subject/SubjectService.java
backend/src/main/java/com/borathings/borapagar/user/UserEntity.java
backend/src/main/java/com/borathings/borapagar/user/UserRepository.java
backend/src/main/resources/db/migration/V1.20240814185314__ALTER_SOFT_DELETE_TABLES_CHANGE_DELETED_TO_DELETED_AT.sql
backend/src/main/resources/db/migration/V1.20240814185314__ALTER_USER_TABLE_ADD_DELETED_UPDATED_CREATED.sql
backend/src/test/java/com/borathings/borapagar/course/CourseControllerTests.java
backend/src/test/java/com/borathings/borapagar/course/CourseServiceTests.java
backend/src/test/java/com/borathings/borapagar/subject/SubjectServiceTests.java

Implementa soft-delete para garantir que nenhum dado seja perdido por acidente, permitindo reversão de deletes.
- Implementado `SoftDeletableModel`
- classes que implementam soft delete herdam de `SoftDeletableModel`
- alteração do campo de soft delete de `deleted` para `deleted_at`, por ser mais informativo
Closes #47 
testes
soft-delete cascade

feat: altera soft delete de `deleted` para `deleted_at` e  implementa função

---

backend/src/main/java/com/borathings/borapagar/user/UserController.java
backend/src/main/java/com/borathings/borapagar/user/UserMapper.java
backend/src/main/java/com/borathings/borapagar/user/UserRepository.java
backend/src/main/java/com/borathings/borapagar/user/dto/UserDTO.java
backend/src/main/java/com/borathings/borapagar/user/impl/UserControllerImpl.java
backend/src/test/java/com/borathings/borapagar/user/UserControllerTests.java
backend/src/test/java/com/borathings/borapagar/user/UserMapperTests.java

O cookie armazenado no navegador não diz muito sobre o usuário atual, essa PR adiciona um endpoint que com base nesse cookie consegue todas as informações do usuário atualmente logado
- Criação do UserMapper
- Endpoint para capturar e mostrar o usuário logado
Testar

feat: adiciona endpoint `/users/me`

---

backend/src/main/java/com/borathings/borapagar/department/DepartmentEntity.java
backend/src/main/java/com/borathings/borapagar/subject/SubjectEntity.java
backend/src/main/java/com/borathings/borapagar/subject/dto/SubjectDTO.java
backend/src/main/resources/db/migration/V1.20240815185637__CREATE_DEPARTMENT_TABLE_AND_RELATION_WITH_SUBJECT.sql
backend/src/test/java/com/borathings/borapagar/subject/SubjectControllerTests.java

closes #92 
Visando acelerar a integração com o bora raspar, é legal termos esta entidade no nosso banco, já que as turmas, professores e disciplinas são todas separadas por departamento.
- Criação da entidade de departamento e o seu relacionamento com disciplinas
Faltou a validação se o `departmentId` passado pelo usuário no endpoint realmente corresponde a um departamento do banco de dados. Como este endpoint nunca será usado pelo usuário principal do app, achei desnecessário esta validação no momenot.

feat: entidade de departamento

---

backend/src/main/java/com/borathings/borapagar/core/SoftDeletableRepository.java

O método `findAll` do `SoftDeletableRepository` está fazendo o contrário do que a gente pensou que estava fazendo por conta de um `NOT` mal colocado. 
- `findAll` agora retorna todos os registros que não foram deletados.

fix: Problema no `SoftDeletableRepository`

---

backend/src/main/java/com/borathings/borapagar/department/DepartmentEntity.java
backend/src/main/java/com/borathings/borapagar/subject/SubjectEntity.java
backend/src/main/resources/db/migration/V1.20240822210622__CREATE_PREREQUISITE_TABLE.sql

Esse relacionamento é fundamental para as regras de negócio da aplicação pois um usuário só pode colocar uma disciplina em seu semestre se já pagou todos os pré-requisitos.
- Adicionando novos campos na entidade de disciplina para incluir os seus pré-requisitos
- Migration para modelar este relacionamento no BD.

feat: relacionamento de pré-requisito

---

backend/src/main/java/com/borathings/borapagar/course/CourseService.java
backend/src/main/java/com/borathings/borapagar/course/dto/CourseDTO.java
backend/src/main/java/com/borathings/borapagar/course/impl/CourseControllerImpl.java
backend/src/main/java/com/borathings/borapagar/subject/SubjectService.java
backend/src/main/java/com/borathings/borapagar/subject/dto/SubjectDTO.java
backend/src/main/java/com/borathings/borapagar/subject/impl/SubjectControllerImpl.java
backend/src/test/java/com/borathings/borapagar/course/CourseServiceTests.java
backend/src/test/java/com/borathings/borapagar/subject/SubjectServiceTests.java

closes #104.
Ficou decidido que faz mais sentido que os services recebam um DTO do que uma entidade, já que os dados ainda não vem completos naquele ponto do código.
<!---
Se muita coisa foi feita, por favor resumir na linha abaixo.
Exemplo:
- Um açaí no capricho
- Uma landing page
- Um som que te faz dançar
--
- Refatoração dos services de subject e de course para que seus métodos recebam DTO's em vez das entidades

refact: usando DTO nos services

---

backend/src/main/java/com/borathings/borapagar/subject/SubjectEntity.java
backend/src/main/resources/db/migration/V1.20240828194040__CREATE_EQUIVALENCES_TABLE.sql

Vai ser necessário para as análises de pré-requisito e do cálculo do progresso do curso.
- Adicionado relacionamento de equivalência entre disciplinas

feat: adicionando relacionamento de equivalência entre disciplinas 

---

backend/src/main/java/com/borathings/borapagar/core/Patcher.java
backend/src/test/java/com/borathings/borapagar/core/PatcherTests.java

O patcher vai ser útil para realizar atualização parcial de entidades. Evitando vários if's checando se os campos são nulos antes de atualizar.
- Adição de um patcher genérico para atualização parcial de qualquer entidade

feat: adicionando patcher

---

backend/src/main/java/com/borathings/borapagar/user_semester/UserSemesterService.java

O nome nada descritivo gerou confusão entre os devs. O nome desta variável agora está mais descritivo
Renomeando os argumentos chamados `id` para `semesterId` no `UserSemesterService`

refact: renomeando 'id' para 'semesterId' no `UserSemesterService`

---

backend/src/main/java/com/borathings/borapagar/user_planning/UserPlanningController.java
backend/src/main/java/com/borathings/borapagar/user_planning/UserPlanningRepository.java
backend/src/main/java/com/borathings/borapagar/user_planning/UserPlanningService.java
backend/src/main/java/com/borathings/borapagar/user_planning/impl/UserPlanningControllerImpl.java
backend/src/test/java/com/borathings/borapagar/user_planning/UserPlanningControllerTests.java
backend/src/test/java/com/borathings/borapagar/user_planning/UserPlanningServiceTests.java

Usuário agora consegue remover uma disciplina do seu planejamento de matérias para o semestre.
Endpoint para que usuário possa deletar uma disciplina do seu planejamento e seus testes

feat: endpoint para remover disciplina do planejamento

---

backend/src/main/java/com/borathings/borapagar/user_planning/UserPlanningController.java
backend/src/main/java/com/borathings/borapagar/user_planning/UserPlanningService.java
backend/src/main/java/com/borathings/borapagar/user_planning/dto/UpdateUserPlanningDTO.java
backend/src/main/java/com/borathings/borapagar/user_planning/impl/UserPlanningControllerImpl.java
backend/src/main/java/com/borathings/borapagar/user_semester/UserSemesterService.java
backend/src/test/java/com/borathings/borapagar/user_planning/UserPlanningControllerTests.java
backend/src/test/java/com/borathings/borapagar/user_planning/UserPlanningServiceTests.java

O usuário agora pode mudar o semestre que pretende cursar a disciplina. Depende de #129 
- Endpoint para atualizar o semestre que o usuário irá cursar a disciplina e seus testes.

feat: adicionando endpoint para mudar o semestre planejado para uma disciplina

---

backend/src/main/java/com/borathings/borapagar/core/ApplicationConstants.java
backend/src/main/java/com/borathings/borapagar/user_planning/UserPlanningController.java
backend/src/main/java/com/borathings/borapagar/user_planning/UserPlanningService.java
backend/src/main/java/com/borathings/borapagar/user_planning/impl/UserPlanningControllerImpl.java
backend/src/test/java/com/borathings/borapagar/user_planning/UserPlanningControllerTests.java
backend/src/test/java/com/borathings/borapagar/user_planning/UserPlanningServiceTests.java

Com este endpoint o usuário agora pode marcar se uma disciplina que está no planejamento foi concluída ou não.
- Endpoint que alterna o status de conclusão da disciplina no banco + testes.

feat: endpoint que altera estado de conclusão da disciplina 

---

backend/pom.xml

Esta biblioteca vai facilitar a serialização das entidades e o partial update.
- Adição da biblioteca [MapStruct](https://mapstruct.org/documentation/stable/reference/html/#Preface) no projeto
- Correções de formatação no arquivo `pom.xml`

feat: adicionando biblioteca MapStruct

---

backend/src/main/java/com/borathings/borapagar/professor/ProfessorEntity.java
backend/src/main/resources/db/migration/V1.20240904234951__CREATE_PROFESSOR_TABLE.sql

Preparação para o script de inserir professor/departamento com base nos JSONs raspados
Criado a entidade de professor e a migration da tabela `professor`
Lidar com serialização

feat: Criação da entidade do professor

---

backend/pom.xml
backend/src/main/java/com/borathings/borapagar/user_semester/UserSemesterController.java
backend/src/main/java/com/borathings/borapagar/user_semester/UserSemesterEntity.java
backend/src/main/java/com/borathings/borapagar/user_semester/UserSemesterMapper.java
backend/src/main/java/com/borathings/borapagar/user_semester/UserSemesterService.java
backend/src/main/java/com/borathings/borapagar/user_semester/dto/request/CreateUserSemesterDTO.java
backend/src/main/java/com/borathings/borapagar/user_semester/dto/request/UpdateUserSemesterDTO.java
backend/src/main/java/com/borathings/borapagar/user_semester/dto/response/DefaultUserSemesterDTO.java
backend/src/main/java/com/borathings/borapagar/user_semester/dto/response/UserSemesterResponseDTO.java
backend/src/main/java/com/borathings/borapagar/user_semester/impl/UserSemesterControllerImpl.java
backend/src/test/java/com/borathings/borapagar/user_semester/UserSemesterControllerTests.java
backend/src/test/java/com/borathings/borapagar/user_semester/UserSemesterServiceTests.java

Ao utlizar mappers e a biblioteca MapStruct nós aprimoramos bastante a serialização das entidades no geral. Esta PR contempla a entidade de semestre de usuário.
- Adicionando Mapper de semestre de usuário
- Refatoração dos arquivos para as novas mudanças
- Refatoração dos testes para as novas mudanças

feat: serialização da entidade de semestre de usuário

---

backend/pom.xml
backend/src/main/java/com/borathings/borapagar/user/UserController.java
backend/src/main/java/com/borathings/borapagar/user/UserMapper.java
backend/src/main/java/com/borathings/borapagar/user/dto/UserDTO.java
backend/src/main/java/com/borathings/borapagar/user/dto/response/DefaultUserDTO.java
backend/src/main/java/com/borathings/borapagar/user/dto/response/UserResponseDTO.java
backend/src/main/java/com/borathings/borapagar/user/impl/UserControllerImpl.java
backend/src/test/java/com/borathings/borapagar/user/UserControllerTests.java
backend/src/test/java/com/borathings/borapagar/user/UserMapperTests.java

Para deixar a entidade de usuário pronta para extensões, é bom que ela siga o padrão das outras entidades em usar o MapStruct.
- Refatoração do UserMapper para novo padrão utilizando MapStruct

refact: reescrevendo mapper de usuário

---

frontend/src/components/PeriodCard.vue
frontend/src/views/DashboardView.vue

- Adicionar animação no card de período da dashboard. closes #134 
-  Adiciona animação no card de período da dashboard

style(frontend): add slide animation to Periodcard

---

backend/src/main/java/com/borathings/borapagar/config/AuthConfig.java

Erro no swagger, impedindo visualização dos endpoints
A url do swagger foi corrigida e sua prioridade no `SecurityFilterChain` foi aumentada
**Screenshots**
Swagger antes:
Swagger depois:

Fix: erro de autenticação no swagger

---

backend/src/main/java/com/borathings/borapagar/user/UserEntity.java
backend/src/main/resources/db/migration/V1.20240913202952__ADD_LEVEL_AND_IEA_COLUMNS_TO_USER.sql

relacionado com a issue #150. Esses são alguns (espero que todos) os campos que faltam para a entidade de usuário.
Adicionado as colunas de IEA e de período atual para o usuário.

feat: adicionando colunas de IEA e de período atual do usuário

---

frontend/src/App.vue
frontend/src/pages/ConsultSubjetcs/ConsultSubjectsView.vue
frontend/src/pages/Dashboard/DashboardView.vue
frontend/src/pages/Friends/FriendsView.vue
frontend/src/router/index.js

Componentes SimboraChat e NavBar estavam em algumas páginas, causando repetições desnecessárias
Removido os componentes das páginas individuais e adicionado no arquivo App.vue

refact:Centralize NavBar and SimboraChat components

---

frontend/src/components/CardSubjects.vue
frontend/src/pages/ConsultSubjetcs/ConsultSubjectsController.js
frontend/src/pages/ConsultSubjetcs/ConsultSubjectsMockData.json
frontend/src/pages/ConsultSubjetcs/ConsultSubjectsView.vue

Na pagina de disciplinas, o código antigo estava utilizando dados estáticos para renderizar os SubjectCards
Utilização de um controller para receber os dados dos subjects, atualmente ainda dados mockados.

refact: Fetch discipline data from a MockData

---

backend/pom.xml
backend/src/main/java/com/borathings/borapagar/config/AuthConfig.java
backend/src/main/resources/application.yaml
backend/src/test/java/com/borathings/borapagar/ping/PingControllerTests.java
backend/src/test/java/com/borathings/borapagar/user/UserControllerTests.java
backend/src/test/java/com/borathings/borapagar/utils/AuthenticatedMockMvc.java

O backend não servirá como resource server, este papel será do SIGAA, o backend atuará como client com o SIGAA, para que o frontend consuma recursos do backend será necessário apenas o cookie após login bem-sucedido
Removido a configuração do OAuth2 Resource server

refactor: remove código do OAuth2 de resource server

---

backend/pom.xml
backend/src/main/java/com/borathings/borapagar/auth/CustomOAuth2AuthorizationRequestResolver.java
backend/src/main/java/com/borathings/borapagar/auth/CustomOidcUserService.java
backend/src/main/java/com/borathings/borapagar/auth/OAuth2AuthenticationSuccessHandler.java
backend/src/main/java/com/borathings/borapagar/config/OAuth2Config.java
backend/src/main/java/com/borathings/borapagar/config/SwaggerConfig.java
backend/src/main/java/com/borathings/borapagar/config/WebConfig.java
backend/src/main/java/com/borathings/borapagar/core/ApplicationConstants.java
backend/src/main/java/com/borathings/borapagar/core/Patcher.java
backend/src/main/java/com/borathings/borapagar/core/SoftDeletableRepository.java
backend/src/main/java/com/borathings/borapagar/core/exception/ApiException.java
backend/src/main/java/com/borathings/borapagar/core/exception/ApiFieldException.java
backend/src/main/java/com/borathings/borapagar/core/exception/GlobalExceptionHandler.java
backend/src/main/java/com/borathings/borapagar/ping/PingController.java
backend/src/main/java/com/borathings/borapagar/ping/impl/PingControllerImpl.java
backend/src/main/java/com/borathings/borapagar/user/UserEntity.java
backend/src/main/java/com/borathings/borapagar/user/UserService.java
backend/src/main/java/com/borathings/borapagar/user/impl/UserControllerImpl.java
backend/src/test/java/com/borathings/borapagar/auth/CustomOAuth2AuthorizationRequestResolverTest.java
backend/src/test/java/com/borathings/borapagar/auth/CustomOidcUserServiceTests.java
backend/src/test/java/com/borathings/borapagar/auth/OAuth2AuthenticationSuccessHandlerTest.java
backend/src/test/java/com/borathings/borapagar/core/PatcherTests.java
backend/src/test/java/com/borathings/borapagar/ping/PingControllerTests.java
backend/src/test/java/com/borathings/borapagar/user/UserControllerTests.java
backend/src/test/java/com/borathings/borapagar/user/UserMapperTests.java
backend/src/test/java/com/borathings/borapagar/user/UserServiceTests.java

O Palantir favorece linhas com mais caracteres e funções lambdas, coisas comum no projeto atual, tornando a leitura mais simples
Alterado formatter de Google Java Formatter para Palantir

chore: Muda formater para Palantir

---

.github/workflows/backend_test_coverage.yml

adiciona env necessária para o projeto buildar

fix: Backend test coverage CI

---

backend/pom.xml
backend/src/test/java/com/borathings/borapagar/user/UserControllerTests.java
backend/src/test/java/com/borathings/borapagar/user/UserMapperTests.java

Permitir utilizar features disponíveis apenas em versões mais recentes e garantir que atualizações futuras não sejam complicadas
ex: Há uma feature que facilita o envio do token do SIGAA nas requisições, mas está disponível somente a partir da 3.4.1 do spring boot, estavamos na 3.3.0
Bump da versão de algumas dependências e melhoria de testes já existentes

refactor: atualiza dependências

---

backend/src/main/java/com/borathings/borapagar/student/index/StudentIndexEntity.java
backend/src/main/resources/db/migration/V1.20250210194634__CREATE_STUDENT_INDEX_TABLE.sql

- [] Relacionei todas as issues na seção de "Development" da PR
Facilitar inserção e consulta mantendo o padrão do SIGAA
Alterna a relação de 1:1 de estudante <-> indices para 1:N

refactor: split index into 1:N

---

src/main/java/com/borathings/borapagar/student/StudentService.java

Durante o processo de desenvolvimento o nome de cada índice estava hardcoded de forma errada
Corrigido para usar o número do índice com base no id do índice

fix: remove nome do índice hardcoded

---

createMigration
src/main/java/com/borathings/borapagar/student/StudentService.java
src/main/java/com/borathings/borapagar/student/transcript/TranscriptComponentEntity.java
src/main/java/com/borathings/borapagar/student/transcript/TranscriptComponentRepository.java
src/main/java/com/borathings/borapagar/student/transcript/TranscriptComponentService.java
src/main/java/com/borathings/borapagar/student/transcript/dto/TranscriptComponentDTO.java
src/main/java/com/borathings/borapagar/task/AfterLoginService.java
src/main/resources/db/migration/V1.20250225155635__CREATE_TRANSCRIPT_COMPONENT_TABLE.sql
src/test/java/com/borathings/borapagar/student/transcript/TranscriptComponentServiceTest.java
src/test/java/com/borathings/borapagar/student/transcript/dto/TranscriptComponentDTOTest.java
src/test/java/com/borathings/borapagar/task/AfterLoginServiceTest.java

Parte final da obtenção de informações necessárias do usuário
- Criado tabela referente as componentes do histórico do usuário
- Criado a task para recuperar esses componentes
- Adicionar a turma (?)
- Fazer relação com informações adicionais como componente e professor

feat: inserção de cúrriculo do usuário

---

pom.xml
src/main/java/com/borathings/borapagar/student/StudentService.java
src/main/java/com/borathings/borapagar/student/interest/StudentSubjectInterestController.java
src/main/java/com/borathings/borapagar/student/interest/StudentSubjectInterestEntity.java
src/main/java/com/borathings/borapagar/student/interest/StudentSubjectInterestRepository.java
src/main/java/com/borathings/borapagar/student/interest/StudentSubjectInterestService.java
src/main/java/com/borathings/borapagar/student/interest/dto/StudentSubjectInterestDTO.java
src/main/java/com/borathings/borapagar/student/interest/dto/StudentSubjectInterestSemesterDTO.java
src/main/java/com/borathings/borapagar/student/interest/impl/StudentSubjectInterestControllerImpl.java
src/main/resources/db/migration/V1.20250320235847__CREATE_STUDENT_SUBJECT_INTERESTS_TABLE.sql
src/test/java/com/borathings/borapagar/student/interest/StudentSubjectInterestServiceTest.java

Usuário (Estudante) demonstrar interesse em uma disciplina
- API para listar/criar/remover  interesse em uma disciplina
- Desenvolver a entidade Disciplina para ter informações mais ricas

feat: show interest in subject

---

src/main/java/com/borathings/borapagar/student/StudentController.java
src/main/java/com/borathings/borapagar/student/StudentRepository.java
src/main/java/com/borathings/borapagar/student/StudentService.java
src/main/java/com/borathings/borapagar/student/impl/StudentControllerImpl.java
src/main/java/com/borathings/borapagar/user/UserController.java
src/main/java/com/borathings/borapagar/user/UserService.java

Permitir acessar informações do perfil de estudante de um usuário logado
Adicionado rota `/api/users/me`

feat: adiciona rota /api/students/me

---

pom.xml

chore: add flyway deploy config

---

src/main/java/com/borathings/borapagar/student/StudentController.java
src/main/java/com/borathings/borapagar/student/StudentMapper.java
src/main/java/com/borathings/borapagar/student/StudentService.java
src/main/java/com/borathings/borapagar/student/dto/StudentDTO.java
src/main/java/com/borathings/borapagar/student/dto/StudentResponseDTO.java
src/main/java/com/borathings/borapagar/student/impl/StudentControllerImpl.java
src/test/java/com/borathings/borapagar/student/StudentMapperTest.java

- [] A PR está relacionada a uma ou mais issue
Arrumar erro na hora do createInstituionalStudent

fix : Fixed student response error

---

src/main/java/com/borathings/borapagar/student/interest/StudentSubjectInterestController.java
src/main/java/com/borathings/borapagar/student/interest/StudentSubjectInterestService.java
src/main/java/com/borathings/borapagar/student/interest/dto/StudentSubjectAddInterestDTO.java
src/main/java/com/borathings/borapagar/student/interest/dto/StudentSubjectInterestDTO.java
src/main/java/com/borathings/borapagar/student/interest/dto/StudentSubjectInterestSemesterDTO.java
src/main/java/com/borathings/borapagar/student/interest/impl/StudentSubjectInterestControllerImpl.java
src/main/java/com/borathings/borapagar/subject/SubjectSigaaClient.java
src/main/java/com/borathings/borapagar/subject/dto/ComponentDTO.java
src/test/java/com/borathings/borapagar/student/interest/StudentSubjectInterestServiceTest.java

Para não ter que guardar todos os components do SIGAA, este código faz fetch do component com base no seu ID para retornar as informações importantes, mantendo apenas o id da disciplina no banco
- Fetch das informações do componente diretamente do SIGAA
adicionar o cache

feat: retorna dados de um componente diretamente do SIGAA

---

src/main/java/com/borathings/borapagar/student/StudentController.java
src/main/java/com/borathings/borapagar/student/StudentService.java
src/main/java/com/borathings/borapagar/student/impl/StudentControllerImpl.java

Encontrar informações do estudante com base no seu ID libera algumas features como ver perfil
Adicionado rota que retorna perfil do usuário com base no seu id do sistema

feat: Encontra estudante com base no seu id

---

src/main/java/com/borathings/borapagar/user/UserController.java
src/main/java/com/borathings/borapagar/user/UserService.java
src/main/java/com/borathings/borapagar/user/impl/UserControllerImpl.java

Motivação para a criação da PR
Encontrar informações do usuário com base no seu ID
O que foi feito
Adicionado rota que retorna informações do usuário com base no seu id do sistema

feat: Encontra usuário por id
